version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27018:27017"
    networks:
      - backend_net
    environment:
      # Use variables from .env
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - mongo_data:/data/db
  
  mongo-express:
    image: mongo-express:latest
    container_name: express_container
    ports:
      - "8080:8081"
    networks:
      - backend_net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASS}
    depends_on:
      - mongodb
  
  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    networks:
      - backend_net
    depends_on:
      - mongodb
    environment:
      # We pass these to Flask so it knows how to log in
      - DB_USER=${MONGO_USER}
      - DB_PASS=${MONGO_PASS}
      - DB_HOST=mongodb

volumes:
  mongo_data:

networks:
  backend_net:
    driver: bridge